export const dataBooks = [
    {
        id: 1,
        name: "El Misterio De Salem's Lot",
        author: "Stephen King",
        category: "terror",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt nostrum sequi saepe deserunt illum quam optio temporibus aliquid impedit, sapiente suscipit fugiat autem iste corrupti nihil atque veniam libero eum.",
        image: "https://http2.mlstatic.com/D_NQ_NP_638253-MLA53781047429_022023-O.webp",
        stock: "5",
        price: "12199",
    },
    {
        id: 2,
        name: "El Resplandor",
        author: "Stephen King",
        category: "terror",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt nostrum sequi saepe deserunt illum quam optio temporibus aliquid impedit, sapiente suscipit fugiat autem iste corrupti nihil atque veniam libero eum.",
        image: "https://http2.mlstatic.com/D_NQ_NP_679936-MLA33018282359_112019-O.webp",
        stock: "10",
        price: "7379",
    },
    {
        id: 3,
        name: "It",
        author: "Stephen King",
        category: "terror",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt nostrum sequi saepe deserunt illum quam optio temporibus aliquid impedit, sapiente suscipit fugiat autem iste corrupti nihil atque veniam libero eum.",
        image: "https://http2.mlstatic.com/D_NQ_NP_884458-MLU69759024127_062023-O.webp",
        stock: "2",
        price: "14900",
    },
    {
        id: 4,
        name: "Diario De Una Pasion",
        author: "Nicholas Sparks",
        category: "romance",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt nostrum sequi saepe deserunt illum quam optio temporibus aliquid impedit, sapiente suscipit fugiat autem iste corrupti nihil atque veniam libero eum.",
        image: "https://http2.mlstatic.com/D_NQ_NP_716455-MLA50890277421_072022-O.webp",
        stock: "10",
        price: "11299",
    },
    {
        id: 5,
        name: "Orgullo y Prejuicio",
        author: "Jane Austen",
        category: "romance",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt nostrum sequi saepe deserunt illum quam optio temporibus aliquid impedit, sapiente suscipit fugiat autem iste corrupti nihil atque veniam libero eum.",
        image: "https://http2.mlstatic.com/D_NQ_NP_285915-MLA25342914291_022017-O.webp",
        stock: "10",
        price: "9990",
    },
    {
        id: 6,
        name: "Lo que el viento se llevo",
        author: " Margaret Mitchell",
        category: "romance",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt nostrum sequi saepe deserunt illum quam optio temporibus aliquid impedit, sapiente suscipit fugiat autem iste corrupti nihil atque veniam libero eum.",
        image: "https://http2.mlstatic.com/D_NQ_NP_762313-MLA51482441670_092022-O.webp",
        stock: "10",
        price: "39000",
    }
];